name: 4dh
channels:
  - anaconda
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pandas=0.25
  - numpy=1.19.5
  - numba=0.52.0
  - bokeh=2.2.3
  - scipy=1.6.0
  - seaborn=0.11.1
  - nb_conda=2.2.1
  - jupyter_contrib_nbextensions=0.5.1
  - jupyter=1.0.0
  - ipywidgets=7.6.3
  - ipyparallel=6.3.0
  - hdf5=1.10.4
  - kallisto=0.46.0
  - loompy=3.0.6
  - r-base=4.0.3
  - r-curl=4.3
  - r-matrix.utils
  - r-sf
- pip:
  - scanpy==1.7.0rc1
  - leidenalg==0.8.3
  - rpy2==3.4.2
  - anndata2ri==1.0.6
  - scvelo==0.2.2
  - triku==1.3.1
  - ray==1.1.0
  - phate==1.0.4
  - harmonypy==0.0.5
  - bbknn==1.4.0
  - umap-learn==0.4.6
  - scrublet==0.2.3
  - cellassign==0.0.1
